services:
  - type: web
    name: media-upload
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: media-upload-db
          property: connectionString

databases:
  - name: media-upload-db
    plan: free